import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./slider.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* TODO: add this to see the debug screen "debug-screens" */}
      <body className={cn(inter.className)}>
        <main id="portal-container"></main>
        {/* Header */}
        <Navbar />

        {/* General Pages */}
        {children}

        <ToastContainer />
      </body>
    </html>
  );
}
